libs=-lcsp ${platlibs} -lm
b=${bin}

all: clean $b/1$E $b/2$E $b/spawnexit$E
	
.c.$O:
	${CC} ${CFLAGS} ${inc} -c -o $@ $<
	
$b/1$E: 1.$O
	${CC} ${LDFLAGS} -o $@ $? ${libs}
	
$b/2$E: 2.$O
	${CC} ${LDFLAGS} -o $@ $? ${libs}
	
$b/spawnexit$E: spawnexit.$O
	${CC} ${LDFLAGS} -o $@ $? ${libs}
	
clean:
	rm -f $b/1$E 1.$O \
		$b/2$E 2.$O \
		$b/spawnexit$E spawnexit.$O
