libs=-lcsp ${platlibs} -lm
CFLAGS+=${inc} -I${PREFIX}/include
b=${bin}

all: clean \
  $b/1$E \
  $b/spawnexit$E \
  $b/chanrecvp$E \
  $b/closedchan$E \
  $b/openedchan$E \
  $b/random$E
  
.c.$O:
	${CC} ${CFLAGS} -c -o $@ $<
	
c=${CC} ${LDFLAGS} -o $@ $? ${libs}
$b/1$E: 1.$O
	$c
$b/spawnexit$E: spawnexit.$O
	$c
$b/chanrecvp$E: chanrecvp.$O
	$c
$b/closedchan$E: closedchan.$O
	$c
$b/openedchan$E: openedchan.$O
	$c
$b/random$E: random.$O
	$c

clean:
	rm -f \
		$b/1$E 1.$O \
		$b/spawnexit$E spawnexit.$O \
		$b/chanrecvp$E chanrecvp.$O \
		$b/closedchan$E closedchan.$O \
		$b/openedchan$E openedchan.$O \
		$b/random$E random.$O
